### ISSUE TITLE
Define website structure

### ISSUE THREAD

**Issue by psxjpm** [NIME-conference/diversity-wiki#4]
Define sections (e.g. diversity data, diversity resources as downloadable files? -papers, and slides)

**Comment by psxjpm** [comment]
Proposed sections:

-Announcements (past and future workshops)
-Resources (could add an entry about the diversity wheel, another entry reporting on the workshop, etc)
-Actions (ongoing actions like the ESL editing assistance programme)
-Contribute (guidelines to contribute resources to the wiki)

**Comment by transientstatic** [comment]
Where does this actually show up as a web page?

I’d like to add some bits- the Jan meeting notes for sure.

Laurel

On 11 Mar 2021, at 02:34, Juan Martinez Avila ***@***.******@***.***>> wrote:



Proposed sections:

-Announcements (past and future workshops)
-Resources (could add an entry about the diversity wheel, another entry reporting on the workshop, etc)
-Actions (ongoing actions like the ESL editing assistance programme)
-Contribute (guidelines to contribute resources to the wiki)

**Comment by psxjpm** [comment]
Currently here: https://psxjpm.gitbook.io/diversity-at-nime/announcements/online-diversity-workshop-jan-2021 

Though it should be migrated to a nime.org subdomain at some point. 

Note I made two branches, `main` and `draft`. My rationale here is to have revisions in the draft branch and then merge that to main when it's ready to publish.

**Comment by transientstatic** [comment]
Ace.

I’m assuming only what is on main shows up in gitbook?

Which may explain two separate repository for the Eco guys...

On 19 Mar 2021, at 21:55, Juan Martinez Avila ***@***.******@***.***>> wrote:



Currently here: https://psxjpm.gitbook.io/diversity-at-nime/announcements/online-diversity-workshop-jan-2021

Though it should be migrated to a nime.org<http://nime.org> subdomain at some point.

Note I made two branches, main and draft. My rationale here is to have revisions in the draft branch and then merge that to main when it's ready to publish.
